name: Automatic Backport

on:
  workflow_dispatch:
    
permissions:
  contents: write
  actions: write    
  
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and PRs

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install cherry-picker
        run: pip install cherry-picker
        
      - name: Set Git User Identity
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Get Commit SHA
        id: get_commit_sha
        run: |
          # Extract the commit SHA associated with the PR
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMIT_SHA=$(git log -1 --format="%H" FETCH_HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          
      - name: Run backport automation Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./backport.py "123" "2.0" "${{ secrets.GITHUB_TOKEN }}"
