name: Automatic backport action

on:
  push:
    types: ["labeled", "closed"]
    branches: ['main']
permissions:
  contents: read
  packages: write
  pull-requests: write
  checks: write
  
jobs:
  backport:
    name: Backport PR
    if: github.event.pull_request.merged == true && !(contains(github.event.pull_request.labels.*.name, 'backport'))
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub Context
        run: echo "${{ toJson(github) }}"
      - name: Backport Action
        uses: sorenlouv/backport-github-action@ad888e978060bc1b2798690dd9d03c4036560947
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-to-

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log        
          
