name: RandomeError
on:
  push:
    branches: ["main"]

jobs:
  display-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub Context
        run: echo "${{ toJson(github) }}"
